### PR TITLE
libexif/exif-gps-ifd.c: fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with gcc 4.8 raised since version 0.6.23 and https://github.com/libexif/libexif/commit/e12c3529813cd16d50bf0a1c759093e1039dffec:

```
exif-gps-ifd.c: In function 'exif_get_gps_tag_info':
exif-gps-ifd.c:62:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < sizeof(exif_gps_ifd_tags) / sizeof(ExifGPSIfdTagInfo); ++i) {
   ^
exif-gps-ifd.c:62:3: note: use option -std=c99 or -std=gnu99 to compile your code
```

Fixes:
 - http://autobuild.buildroot.org/results/7dd222e06d1e6611449fb8fe7516817c9ad43d65

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by ndim** [comment]
Can't we expect C99 in 2021?

**Comment by ffontaine** [comment]
Unfortunately, embedded systems sometimes uses pretty old toolchains. However, you're free to mandate C99. In this case, I'll reflect this new dependency on buildroot side to disable libexif with these old toolchains.

**Comment by ndim** [comment]
I know embedded systems sometimes use old toolchains, so I was surprised and annoyed about lack of C99 support ten years ago in 2011. I am surprised and resigned that lack of C99 support is still a thing in 2021.

Well, if libexif is supposed to compile with C89 (and many idications suggest that), we should make sure that for more modern compilers, we *do* compile with a `-std=c90` parameter or similar for all builds, not just for the Travis builds, and therefore catch C99isms earlier.

**Comment by ndim** [comment]
Now I am wondering how this could end up in the code without getting caught.

`configure.ac´ *does* set `AM_CFLAGS` to contain `-ansi --pedantic=error` when `$GCC` is "yes", after all.

**Comment by dfandrich** [comment]
On Wed, Sep 15, 2021 at 03:46:26PM -0700, Hans Ulrich Niedermann wrote:
> Well, if libexif is supposed to compile with C89 (and many idications suggest
> that), we should make sure that for more modern compilers, we do compile with a
> -std=c90 parameter or similar for all builds, not just for the Travis builds,
> and therefore catch C99isms earlier.

We have/had such a build on Travis, but with Travis effectively gone, we should
move all those builds to Github Actions or something else.

**Comment by ndim** [comment]
> On Wed, Sep 15, 2021 at 03:46:26PM -0700, Hans Ulrich Niedermann wrote:
> > Well, if libexif is supposed to compile with C89 (and many idications suggest that), we should make sure that for more modern compilers, we do compile with a -std=c90 parameter or similar for all builds, not just for the Travis builds, and therefore catch C99isms earlier.

> We have/had such a build on Travis, but with Travis effectively gone, we should move all those builds to Github Actions or something else.

Granted, but it would still be useful if local builds failed as well, not just whatever CI system happens to be working properly that day.
